id: P9C37C008
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1PD90033
  instance_id: http://purl.bdrc.io/resource/IE1PD90033
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangZh
  title:
    zh-latn-pinyin-x-ndia:
    - a ba zhou zhi
  alt_title:
    bo:
    - རྔ་བ་ཁུལ་ས་གནས་ལོ་རྒྱུས།
    en-x-mixed:
    - Rṅa-ba khul sa gnas lo rgyus /Si-khron Źiṅ-chen Rṅa-ba Bod rigs chaʼaṅ rigs
      raṅ skyoṅ khul sa gnas lo rgyus rtsom sgrig u yon lhan khaṅ gis bsgrigs.
  author: None
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    ee476f6fdef84fa6a939cbab16a8de7a:
      title: པོད ༡་རྔ་བ་ཁུལ་ས་གནས་ལོ་རྒྱུས
      volume_number: 1
      base_file: UT1PD90033_I2DB88005_0000.txt
      reference: http://purl.bdrc.io/resource/VL289F7A4162F22877
      image_group: I2DB88005
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1PD90033
  - http://purl.bdrc.io/resource/MW1PD90033
  ocr_software: Namsel
created_at: '2021-12-22T11:03:46.159718'
last_modified_at: '2021-12-22T11:03:46.159733'
statistics:
  total_words: 384053
  total_non_words: 71138
quality:
  non_words_ratio: 0.19
